const PersonalWorkspaceProfile = require("../models/PersonalWorkspaceProfile");
const ResearchResource = require("../models/ResearchResource");
const UNIVERSAL_PERSONAL_PERMISSIONS=["view_public_data","explore_electoral_geography","view_results","view_candidates","save_items","use_ai_analyzer","use_research_tools","create_research_projects","export_public_data","manage_personal_campaigns","manage_personal_field_operations","manage_personal_tasks","read_ghana_politics_news","read_ghana_governance_news","read_ghana_economy_news"];
const DEFINITIONS={
 personal_use:{label:"Personal / Civic User",description:"Explore public political and electoral information and run your own civic research, campaign planning and field work.",accessProfile:"public_read",permissions:UNIVERSAL_PERSONAL_PERMISSIONS},
 researcher:{label:"Researcher",description:"Conduct structured political, electoral and civic research using public datasets and documented sources, with campaign and field-work tools available in the personal workspace.",accessProfile:"research_read",permissions:[...UNIVERSAL_PERSONAL_PERMISSIONS,"compare_regions","save_research","source_verification"]},
 journalist:{label:"Journalist",description:"Investigate, verify and report on public political and electoral developments, with research, campaign-planning and field-work tools available in the personal workspace.",accessProfile:"journalist_read",permissions:[...UNIVERSAL_PERSONAL_PERMISSIONS,"source_verification","fact_check","press_calendar","newsroom","editorial_calendar"]}
};
const ALL=["personal_use","researcher","journalist"];
const DEFAULT=[
 ["electoral-geography","Electoral Geography Explorer","electoral_geography","Navigate Ghana's regions, constituencies and polling stations.",ALL,"public",["browse","filter","compare"],"/research"],["election-results","Election Results Explorer","election_results","Explore permitted public election results by election and geography.",ALL,"public",["filter","compare","visualize"],"/results"],["candidate-directory","Candidate Directory","candidates","Review public candidate profiles, party affiliation and constituency context.",ALL,"public",["search","compare","save"],"/research"],["party-directory","Political Party Directory","parties","Review public party information and election participation.",ALL,"public",["search","compare"],"/research"],["research-datasets","Research Dataset Library","research_data","Structured public datasets for political and electoral research.",ALL,"research",["preview","filter","export"],"/research"],["survey-builder","Survey & Field Research Builder","research_data","Create opinion polls, election surveys, exit polls, community assessments and issue research.",ALL,"research",["create","target","collect","analyze"],"/research"],["source-library","Source & Provenance Library","public_records","Record source, date, methodology and provenance for research or reporting.",ALL,"research",["save","cite","verify"],"/research"],["methodology","Methodology & Data Dictionary","methodology","Definitions, field descriptions, update cycles and data-quality notes.",ALL,"public",["read","cite"],"/research"],["data-export","Public Data Export","research_data","Export permitted public datasets for analysis and citation.",ALL,"research",["export","filter"],"/research"],["geographic-comparison","Geographic Comparison Lab","electoral_geography","Compare public political indicators across regions and constituencies.",ALL,"research",["compare","visualize"],"/research"],["campaign-planner","Campaign Planner","campaign_operations","Plan campaign objectives, election timelines, activities and workstreams in your own workspace.",ALL,"personal",["create","plan","track"],"/campaigns"],["field-work","Field Work & Task Manager","field_operations","Plan community visits, canvassing, meetings, surveys, polling-station work and logistics.",ALL,"personal",["create","assign","track","complete"],"/field-work"],["ghana-politics","Ghana Politics Briefing","news","Follow current Ghana politics reporting from the connected news feed.",ALL,"public",["read","save"],"/news"],["ghana-governance","Ghana Governance Briefing","news","Follow government and governance developments from the connected news feed.",ALL,"public",["read","save"],"/news"],["ghana-economy","Ghana Economy Briefing","news","Follow Ghana economy and public-finance developments from the connected news feed.",ALL,"public",["read","save"],"/news"]
];
async function ensureResourceCatalog(){for(const[key,title,category,description,audience,access,actions,route]of DEFAULT)await ResearchResource.updateOne({key},{$set:{title,category,description,audience,access,actions,route,isActive:true},$setOnInsert:{key}},{upsert:true})}
const userId=req=>req.user?._id||req.user?.id;
exports.definitions=async(req,res)=>res.json({success:true,data:DEFINITIONS});
exports.getProfile=async(req,res)=>{const profile=await PersonalWorkspaceProfile.findOne({userId:userId(req)});if(!profile)return res.json({success:true,data:null,definitions:DEFINITIONS});const definition=DEFINITIONS[profile.purpose]||DEFINITIONS.personal_use;const missing=definition.permissions.filter(p=>!Array.isArray(profile.permissions)||!profile.permissions.includes(p));if(missing.length){profile.permissions=[...new Set([...(profile.permissions||[]),...definition.permissions])];profile.accessProfile=definition.accessProfile;await profile.save()}return res.json({success:true,data:profile.toObject(),definitions:DEFINITIONS})};
exports.upsertProfile=async(req,res)=>{const{purpose,scopeLevel,regionIds,constituencyIds,pollingStationIds,researchFields,journalismBeat}=req.body||{};const definition=DEFINITIONS[purpose];if(!definition)return res.status(400).json({success:false,message:"Invalid personal workspace purpose. Choose Personal Use, Researcher or Journalist."});const profile=await PersonalWorkspaceProfile.findOneAndUpdate({userId:userId(req)},{$set:{purpose,scopeLevel:scopeLevel||"public_platform",regionIds:Array.isArray(regionIds)?regionIds:[],constituencyIds:Array.isArray(constituencyIds)?constituencyIds:[],pollingStationIds:Array.isArray(pollingStationIds)?pollingStationIds:[],organizationName:"",researchFields:Array.isArray(researchFields)?researchFields:[],journalismBeat:String(journalismBeat||"").trim(),accessProfile:definition.accessProfile,permissions:definition.permissions,onboardingComplete:true}},{upsert:true,new:true,setDefaultsOnInsert:true});return res.json({success:true,data:profile,role:definition})};
exports.resources=async(req,res)=>{await ensureResourceCatalog();const profile=await PersonalWorkspaceProfile.findOne({userId:userId(req)}).lean();const purpose=profile?.purpose||"personal_use";const resources=await ResearchResource.find({isActive:true,audience:purpose}).sort({category:1,title:1}).lean();return res.json({success:true,data:resources,purpose,role:DEFINITIONS[purpose]})};
exports.resourceCatalog=async(req,res)=>{await ensureResourceCatalog();return res.json({success:true,data:await ResearchResource.find({isActive:true}).sort({category:1,title:1}).lean()})};exports.roleDefinitions=DEFINITIONS;
