const PersonalCampaign = require("../models/PersonalCampaign");
const PersonalEvent = require("../models/PersonalEvent");
const PersonalFieldTask = require("../models/PersonalFieldTask");
const Notification = require("../models/Notification");
const mongoose = require("mongoose");
const me=(req)=>req.user?._id||req.user?.id;
const safeDate=v=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d};
const EVENT_TYPES=["Executive Meeting","Campaign Strategy","Polling Agent Training","Community Engagement","Election Operations","Research Meeting","Press Conference","Virtual Meeting"];
const EVENT_PRIORITIES=["Low","Normal","High","Urgent"];
const EVENT_STATUSES=["Scheduled","Confirmed","Pending","Cancelled"];
const CAMPAIGN_STATUSES=["planning","active","paused","completed"];
exports.summary=async(req,res)=>{try{const userId=me(req);if(!userId)return res.status(401).json({success:false,message:"Authentication required."});const [campaigns,activeCampaigns,tasks,openTasks,events,unreadNotifications]=await Promise.all([PersonalCampaign.countDocuments({userId}),PersonalCampaign.countDocuments({userId,status:"active"}),PersonalFieldTask.countDocuments({userId}),PersonalFieldTask.countDocuments({userId,status:{$in:["planned","in_progress"]}}),PersonalEvent.countDocuments({userId}),Notification.countDocuments({recipient:userId,read:false}).catch(()=>0)]);return res.json({success:true,data:{campaigns,activeCampaigns,tasks,openTasks,events,unreadNotifications}})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to load operations summary."})}};
exports.campaigns=async(req,res)=>{try{return res.json({success:true,data:await PersonalCampaign.find({userId:me(req)}).sort({updatedAt:-1}).lean()})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to load campaigns."})}};
exports.createCampaign=async(req,res)=>{try{const userId=me(req),{name,election,geography,objective,status,startDate,endDate}=req.body||{};if(!String(name||"").trim())return res.status(400).json({success:false,message:"Campaign name is required."});const item=await PersonalCampaign.create({userId,name:String(name).trim(),election:String(election||"").trim(),geography:String(geography||"").trim(),objective:String(objective||"").trim(),status:CAMPAIGN_STATUSES.includes(status)?status:"planning",startDate:safeDate(startDate),endDate:safeDate(endDate)});return res.status(201).json({success:true,data:item})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to create campaign."})}};
exports.updateCampaign=async(req,res)=>{try{const userId=me(req);if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid campaign ID."});const current=await PersonalCampaign.findOne({_id:req.params.id,userId});if(!current)return res.status(404).json({success:false,message:"Campaign not found or you are not its creator."});const body=req.body||{};if(body.name!==undefined&&!String(body.name).trim())return res.status(400).json({success:false,message:"Campaign name is required."});const fields=["name","election","geography","objective","status","startDate","endDate"];for(const field of fields)if(body[field]!==undefined){if(field==="status"&& !CAMPAIGN_STATUSES.includes(body[field]))return res.status(400).json({success:false,message:"Invalid campaign status."});current[field]=field.endsWith("Date")?safeDate(body[field]):String(body[field]??"").trim()}await current.save();return res.json({success:true,data:current,message:"Campaign updated successfully."})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to update campaign."})}};
exports.deleteCampaign=async(req,res)=>{try{const userId=me(req);if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid campaign ID."});const item=await PersonalCampaign.findOneAndDelete({_id:req.params.id,userId});if(!item)return res.status(404).json({success:false,message:"Campaign not found or you are not its creator."});return res.json({success:true,message:"Campaign deleted successfully."})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to delete campaign."})}};
exports.events=async(req,res)=>{try{return res.json({success:true,data:await PersonalEvent.find({userId:me(req)}).sort({date:1,startTime:1,updatedAt:-1}).lean()})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to load events."})}};
function eventPayload(body={}){return{title:String(body.title||"").trim(),type:EVENT_TYPES.includes(body.type)?body.type:"Executive Meeting",date:String(body.date||""),startTime:String(body.startTime||""),endTime:String(body.endTime||""),location:String(body.location||"").trim()||"Location not specified",organizer:String(body.organizer||"").trim()||"Current User",priority:EVENT_PRIORITIES.includes(body.priority)?body.priority:"Normal",status:EVENT_STATUSES.includes(body.status)?body.status:"Scheduled"}}
function validateEvent(p){if(!p.title)return"Event title is required.";if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(p.date)||Number.isNaN(new Date(`${p.date}T00:00:00`).getTime()))return"A valid event date is required.";if(!/^\\d{2}:\\d{2}$/.test(p.startTime)||!/^\\d{2}:\\d{2}$/.test(p.endTime))return"Valid start and end times are required.";if(p.endTime<=p.startTime)return"Event end time must be after the start time.";return null}
exports.createEvent=async(req,res)=>{try{const payload=eventPayload(req.body),error=validateEvent(payload);if(error)return res.status(400).json({success:false,message:error});const item=await PersonalEvent.create({userId:me(req),...payload});return res.status(201).json({success:true,data:item})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to create event."})}};
exports.updateEvent=async(req,res)=>{try{const userId=me(req);if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid event ID."});const current=await PersonalEvent.findOne({_id:req.params.id,userId});if(!current)return res.status(404).json({success:false,message:"Event not found or you are not its creator."});const payload=eventPayload({...current.toObject(),...req.body});const error=validateEvent(payload);if(error)return res.status(400).json({success:false,message:error});Object.assign(current,payload);await current.save();return res.json({success:true,data:current,message:"Event updated successfully."})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to update event."})}};
exports.deleteEvent=async(req,res)=>{try{const userId=me(req);if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid event ID."});const item=await PersonalEvent.findOneAndDelete({_id:req.params.id,userId});if(!item)return res.status(404).json({success:false,message:"Event not found or you are not its creator."});return res.json({success:true,message:"Event deleted successfully."})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to delete event."})}};
exports.tasks=async(req,res)=>{try{return res.json({success:true,data:await PersonalFieldTask.find({userId:me(req)}).sort({dueDate:1,updatedAt:-1}).lean()})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to load field tasks."})}};
exports.createTask=async(req,res)=>{try{const userId=me(req),{title,description,area,taskType,status,dueDate,latitude,longitude}=req.body||{};if(!String(title||"").trim())return res.status(400).json({success:false,message:"Task title is required."});const item=await PersonalFieldTask.create({userId,title:String(title).trim(),description:String(description||"").trim(),area:String(area||"").trim(),taskType:["canvass","community_visit","meeting","survey","polling_station","logistics","other"].includes(taskType)?taskType:"other",status:["planned","in_progress","completed","cancelled"].includes(status)?status:"planned",dueDate:safeDate(dueDate),latitude:Number.isFinite(Number(latitude))?Number(latitude):null,longitude:Number.isFinite(Number(longitude))?Number(longitude):null});return res.status(201).json({success:true,data:item})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to create field task."})}};
exports.updateTask=async(req,res)=>{try{const userId=me(req),allowed=["planned","in_progress","completed","cancelled"];if(!mongoose.Types.ObjectId.isValid(req.params.id)||!allowed.includes(req.body?.status))return res.status(400).json({success:false,message:"Invalid task update."});const item=await PersonalFieldTask.findOneAndUpdate({_id:req.params.id,userId},{$set:{status:req.body.status}},{new:true}).lean();if(!item)return res.status(404).json({success:false,message:"Field task not found."});return res.json({success:true,data:item})}catch(e){return res.status(500).json({success:false,message:e.message||"Unable to update field task."})}};
