const crypto=require("crypto");
const mongoose=require("mongoose");
const QRCode=require("qrcode");
const Invitation=require("../models/WorkspaceRoleInvitation");
const WorkspaceDeployment=require("../models/WorkspaceDeployment");
const User=require("../models/User");
const OrganizationMembership=require("../models/OrganizationMembership");
const Election=require("../models/Election");
const PersonalCampaign=require("../models/PersonalCampaign");
const PersonalEvent=require("../models/PersonalEvent");
const id=req=>req.user?._id||req.user?.id;
const hash=t=>crypto.createHash("sha256").update(t).digest("hex");
const token=()=>crypto.randomBytes(32).toString("base64url");
async function target(type,targetId,userId){
 if(!mongoose.Types.ObjectId.isValid(targetId))return null;
 if(type==="election")return Election.findById(targetId).lean();
 if(type==="campaign")return PersonalCampaign.findOne({_id:targetId,userId}).lean();
 if(type==="event")return PersonalEvent.findOne({_id:targetId,userId}).lean();
 return null;
}
exports.searchPeople=async(req,res)=>{try{const q=String(req.query.q||"").trim();if(q.length<2)return res.json({success:true,data:[]});const re=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i");const users=await User.find({$or:[{name:re},{displayName:re},{email:re},{username:re}]},{_id:1,name:1,displayName:1,email:1,username:1,profilePhoto:1}).limit(20).lean();return res.json({success:true,data:users.map(u=>({id:u._id,name:u.name||u.displayName||u.username||u.email,email:u.email,username:u.username,photo:u.profilePhoto}))});}catch(e){return res.status(500).json({success:false,message:"Unable to search users."})}};
exports.create=async(req,res)=>{try{const userId=id(req),b=req.body||{};if(!userId)return res.status(401).json({success:false,message:"Authentication required."});if(!["election","campaign","event"].includes(b.targetType))return res.status(400).json({success:false,message:"Invalid target."});const t=await target(b.targetType,b.targetId,userId);if(!t)return res.status(404).json({success:false,message:"Target not found or not owned by you."});if(!String(b.roleName||"").trim())return res.status(400).json({success:false,message:"Role name is required."});if(!b.personId||!mongoose.Types.ObjectId.isValid(b.personId))return res.status(400).json({success:false,message:"Select a PoliSync user to invite."});const person=await User.findById(b.personId).select("_id").lean();if(!person)return res.status(404).json({success:false,message:"User not found."});const deployment=b.deploymentId&&mongoose.Types.ObjectId.isValid(b.deploymentId)?await WorkspaceDeployment.findOne({_id:b.deploymentId,ownerUserId:userId}).lean():null;const raw=token();const inv=await Invitation.create({tokenHash:hash(raw),createdBy:userId,targetType:b.targetType,targetId:b.targetId,electionId:b.targetType==="election"?b.targetId:(b.electionId||deployment?.electionId||null),roleName:String(b.roleName).trim(),roleDescription:String(b.roleDescription||"").trim(),kind:b.kind||"assignment",personId:b.personId,location:b.location||deployment?.location||null,responsibilities:String(b.responsibilities||deployment?.responsibilities||"").trim(),expiresAt:new Date(Date.now()+Math.min(Math.max(Number(b.expiresInDays)||7,1),30)*86400000)});const base=String(process.env.FRONTEND_URL||"https://polisync-app.onrender.com").replace(/\/$/,"");const url=`${base}/role-invite/${encodeURIComponent(raw)}`;const qrCode=await QRCode.toDataURL(url,{errorCorrectionLevel:"M",margin:2,width:360});return res.status(201).json({success:true,invitation:{id:inv._id,url,qrCode,expiresAt:inv.expiresAt,status:inv.status}})}catch(e){console.error("Role invitation create:",e);return res.status(500).json({success:false,message:"Unable to create role invitation."})}};
async function get(req){const inv=await Invitation.findOne({tokenHash:hash(req.params.token)}).populate("personId","name displayName email username profilePhoto").populate("createdBy","name displayName email").lean();if(!inv)return null;if(inv.status==="pending"&&inv.expiresAt<=new Date())await Invitation.updateOne({_id:inv._id},{$set:{status:"expired"}});return inv}
exports.publicGet=async(req,res)=>{try{const inv=await get(req);if(!inv)return res.status(404).json({success:false,message:"Invitation not found."});return res.json({success:true,invitation:{id:inv._id,targetType:inv.targetType,targetId:inv.targetId,electionId:inv.electionId,roleName:inv.roleName,roleDescription:inv.roleDescription,kind:inv.kind,location:inv.location,responsibilities:inv.responsibilities,person:inv.personId,creator:inv.createdBy,status:inv.status,expiresAt:inv.expiresAt}})}catch(e){return res.status(500).json({success:false,message:"Unable to load invitation."})}};
async function respond(req,res,decision){try{const userId=id(req);if(!userId)return res.status(401).json({success:false,message:"Sign in to respond to this invitation."});const inv=await Invitation.findOne({tokenHash:hash(req.params.token)});if(!inv)return res.status(404).json({success:false,message:"Invitation not found."});if(inv.status!=="pending"||inv.expiresAt<=new Date())return res.status(410).json({success:false,message:"This invitation is no longer active."});if(inv.personId&&String(inv.personId)!==String(userId))return res.status(403).json({success:false,message:"This invitation was addressed to another PoliSync user."});inv.status=decision;inv[decision==="accepted"?"acceptedAt":"declinedAt"]=new Date();await inv.save();if(decision==="accepted"){await WorkspaceDeployment.create({targetType:inv.targetType,targetId:inv.targetId,electionId:inv.electionId,ownerUserId:inv.createdBy,kind:inv.kind,roleName:inv.roleName,roleDescription:inv.roleDescription,personId:userId,personName:"",location:inv.location,responsibilities:inv.responsibilities,status:"assigned"});}return res.json({success:true,status:decision,message:decision==="accepted"?"Role accepted and added to the workspace.":"Role invitation declined."})}catch(e){console.error("Role invitation response:",e);return res.status(500).json({success:false,message:"Unable to process invitation."})}}
exports.accept=(req,res)=>respond(req,res,"accepted");exports.decline=(req,res)=>respond(req,res,"declined");
exports.list=async(req,res)=>{try{const userId=id(req);const data=await Invitation.find({$or:[{createdBy:userId},{personId:userId}]}).sort({createdAt:-1}).limit(200).lean();return res.json({success:true,data})}catch(e){return res.status(500).json({success:false,message:"Unable to load role invitations."})}};
exports.revoke=async(req,res)=>{try{const inv=await Invitation.findOneAndUpdate({_id:req.params.id,createdBy:id(req),status:"pending"},{$set:{status:"revoked"}},{new:true}).lean();if(!inv)return res.status(404).json({success:false,message:"Invitation not found or already processed."});return res.json({success:true,data:inv})}catch(e){return res.status(500).json({success:false,message:"Unable to revoke invitation."})}};
