"use client";

import DashboardShell from "../../../../components/dashboard/DashboardShell";
import DashboardPager from "../../../../components/dashboard/DashboardPager";
import NotificationsPanel from "../../../../components/dashboard/NotificationsPanel";
import ComplaintsReportsPanel from "../../../../components/dashboard/ComplaintsReportsPanel";
import PrivacySecurityPanel from "../../../../components/dashboard/PrivacySecurityPanel";

const HEALTH=["Server Status","Database","API Services","Storage","Security","Backups"];
export default function DashboardOversight(){return <DashboardShell role="super_admin" title="Dashboard Oversight" subtitle="Notifications, complaints, privacy and system health" activeSection="overview"><main className="page"><DashboardPager current="/super-admin/dashboard/oversight"/><section className="hero"><span>PLATFORM OVERSIGHT</span><h2>See what needs attention.</h2><p>Monitoring and governance tools are grouped here for a cleaner operational experience.</p></section><section className="grid"><article className="panel"><header><div className="icon">🔔</div><div><small>01 • ACTIVITY</small><h3>Notifications</h3></div></header><NotificationsPanel initialNotifications={[]}/></article><article className="panel"><header><div className="icon">⚠</div><div><small>02 • REPORTING</small><h3>Complaints & Reports</h3></div></header><ComplaintsReportsPanel initialItems={[]} isSuperAdmin/></article><article className="panel"><header><div className="icon">🔐</div><div><small>03 • PROTECTION</small><h3>Privacy & Security</h3></div></header><PrivacySecurityPanel/></article><article className="panel health"><header><div className="icon">♥</div><div><small>04 • INFRASTRUCTURE</small><h3>System Health</h3></div></header><div className="health-grid">{HEALTH.map(item=><div className="health-item" key={item}><span>✓</span><div><strong>{item}</strong><small>Awaiting live status data</small></div></div>)}</div></article></section></main><style jsx>{styles}</style></DashboardShell>}
const styles=`.page{min-height:100%;padding:clamp(12px,2vw,30px);box-sizing:border-box;background:radial-gradient(circle at 15% 0%,rgba(34,150,83,.18),transparent 30%),#022d16;color:#fff}.hero{padding:12px 2px 20px}.hero>span{color:#f0cd61;font-size:9px;font-weight:950;letter-spacing:2px}.hero h2{margin:6px 0;color:#fff;font-size:clamp(24px,3vw,38px)}.hero p{max-width:720px;margin:0;color:#bcd0c4;font-size:12px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.panel{min-width:0;padding:clamp(14px,1.8vw,22px);border:1px solid rgba(240,205,97,.45);border-radius:20px;background:linear-gradient(145deg,rgba(7,95,43,.94),rgba(2,45,22,.98));box-shadow:0 14px 34px rgba(0,0,0,.18);overflow:hidden;animation:rise .45s ease both}.panel:nth-child(2){animation-delay:.06s}.panel:nth-child(3){animation-delay:.12s}.panel:nth-child(4){animation-delay:.18s}.panel header{display:flex;align-items:center;gap:12px;margin-bottom:15px}.icon{width:44px;height:44px;display:grid;place-items:center;flex:0 0 44px;border:1px solid #f0cd61;border-radius:13px;color:#f0cd61;font-size:20px}.panel small{color:#91a99d;font-size:7px;font-weight:900;letter-spacing:1.4px}.panel h3{margin:3px 0 0;font-size:18px}.health-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.health-item{display:flex;align-items:center;gap:9px;padding:11px;border-radius:12px;background:rgba(0,0,0,.12);border:1px solid rgba(240,205,97,.15)}.health-item>span{width:26px;height:26px;display:grid;place-items:center;border:1px solid #f0cd61;border-radius:50%;color:#f0cd61}.health-item strong{display:block;font-size:9px}.health-item small{display:block;margin-top:3px;color:#91a99d;font-size:7px}.health{min-height:200px}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@media(max-width:760px){.grid{grid-template-columns:1fr}.health-grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.panel{animation:none}}`;
