"use client";

import { useEffect, useState } from "react";

export default function DashboardHeader({ title="Dashboard", subtitle="", role="user", user=null, onMenuClick, onNotificationsClick, onMessagesClick, onProfileClick }) {
  const [weather,setWeather]=useState({loading:true,temperature:null,location:"Location unavailable"});
  useEffect(()=>{let cancelled=false;(async()=>{try{const r=await fetch("/api/weather",{cache:"no-store"});const d=await r.json();if(!cancelled)setWeather({loading:false,temperature:d?.temperature??null,location:d?.location||d?.locationName||"Location unavailable"});}catch{if(!cancelled)setWeather({loading:false,temperature:null,location:"Location unavailable"});}})();return()=>{cancelled=true};},[]);
  const displayName=user?.displayName||user?.fullName||user?.name||"PoliSync User";
  const initials=getInitials(displayName);
  const openMessages=onMessagesClick||(()=>{if(typeof window!=="undefined")window.location.assign("/messages")});
  return <header className="header"><div className="left"><button className="menu" type="button" aria-label="Open navigation" onClick={onMenuClick}>☰</button><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div></div><div className="right"><div className="weather"><span>🌤️</span><div><b>{weather.loading?"--°C":weather.temperature!==null?`${weather.temperature}°C`:"--°C"}</b><small>{weather.location}</small></div></div><button className="icon" type="button" aria-label="Notifications" onClick={onNotificationsClick}>🔔</button><button className="icon" type="button" aria-label="Messages" onClick={openMessages}>💬</button><button className="profile" type="button" aria-label="Open profile" onClick={onProfileClick}><span>{initials}</span><div><b>{displayName}</b><small>{formatRole(role)}</small></div>▾</button></div><style jsx>{`.header{width:100%;min-height:82px;display:flex;align-items:center;justify-content:space-between;gap:20px;padding:14px 28px;background:#fff;border-bottom:1px solid #e7ece8;position:sticky;top:0;z-index:50}.left,.right{display:flex;align-items:center;gap:12px}.left{min-width:0}.left h1{margin:0;color:#0b3d2e;font-size:22px}.left p{margin:3px 0 0;color:#7d8781;font-size:11px}.menu{border:0;background:transparent;font-size:20px}.weather{display:flex;align-items:center;gap:7px;padding-right:10px;border-right:1px solid #e7ece8}.weather span{font-size:18px}.weather b{display:block;color:#344139;font-size:11px}.weather small{display:block;color:#929b95;font-size:8px;max-width:150px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.icon{position:relative;width:36px;height:36px;border:1px solid #e2e9e4;border-radius:10px;background:#fff;cursor:pointer}.profile{display:flex;align-items:center;gap:7px;border:0;background:transparent;text-align:left;cursor:pointer}.profile>span{width:34px;height:34px;display:flex;align-items:center;justify-content:center;border-radius:50%;background:#075f2b;color:#fff;font-weight:800;font-size:10px}.profile b{display:block;color:#344139;font-size:10px}.profile small{display:block;color:#929b95;font-size:8px;margin-top:2px}@media(max-width:760px){.weather,.profile div{display:none}.header{padding:12px 16px}.left h1{font-size:18px}}`}</style></header>;
}

function getInitials(value){return String(value||"PU").trim().split(/\s+/).filter(Boolean).slice(0,2).map((part)=>part[0]).join("").toUpperCase()||"PU";}
function formatRole(role){return String(role||"user").replace(/_/g," ").replace(/\b\w/g,(m)=>m.toUpperCase());}
