"use client";

import dynamic from "next/dynamic";
import { useEffect, useMemo, useState } from "react";
import "leaflet/dist/leaflet.css";

const Map = dynamic(() => import("react-leaflet").then((m) => m.MapContainer), { ssr: false });
const TileLayer = dynamic(() => import("react-leaflet").then((m) => m.TileLayer), { ssr: false });
const Marker = dynamic(() => import("react-leaflet").then((m) => m.Marker), { ssr: false });
const Popup = dynamic(() => import("react-leaflet").then((m) => m.Popup), { ssr: false });
const CircleMarker = dynamic(() => import("react-leaflet").then((m) => m.CircleMarker), { ssr: false });
const Recenter = dynamic(() => import("./ResultsMapRecenter"), { ssr: false });

const GHANA = [7.9465, -1.0232];
const getToken = () => typeof window === "undefined" ? "" : localStorage.getItem("polisync_token") || sessionStorage.getItem("polisync_token") || localStorage.getItem("token") || sessionStorage.getItem("token") || "";
async function api(path) { const token = getToken(); const r = await fetch(path, { cache: "no-store", headers: { Accept: "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }); const j = await r.json().catch(() => ({})); if (!r.ok || j.success !== true) throw new Error(j.message || `Request failed (${r.status}).`); return j; }
const coords = (item) => { if (!item) return null; const lat = Number(item.latitude ?? item.lat ?? item.location?.latitude); const lon = Number(item.longitude ?? item.lon ?? item.lng ?? item.location?.longitude); return Number.isFinite(lat) && Number.isFinite(lon) ? [lat, lon] : null; };
async function geocode(name) { const u = new URL("https://geocoding-api.open-meteo.com/v1/search"); u.searchParams.set("name", `${name}, Ghana`); u.searchParams.set("count", "1"); u.searchParams.set("language", "en"); u.searchParams.set("format", "json"); const r = await fetch(u); const j = await r.json(); const x = j?.results?.[0]; return x ? [Number(x.latitude), Number(x.longitude)] : null; }

export default function ElectionResultsMapExplorer({ title = "Election Results" }) {
  const [elections, setElections] = useState([]), [electionId, setElectionId] = useState("");
  const [regions, setRegions] = useState([]), [constituencies, setConstituencies] = useState([]), [stations, setStations] = useState([]);
  const [regionId, setRegionId] = useState("all"), [constituencyId, setConstituencyId] = useState("all"), [stationId, setStationId] = useState("all");
  const [results, setResults] = useState([]), [nationalStationCount, setNationalStationCount] = useState(0), [regionStationCount, setRegionStationCount] = useState(0);
  const [loading, setLoading] = useState(true), [error, setError] = useState(""); const [focus, setFocus] = useState({ center: GHANA, zoom: 6 });

  useEffect(() => { Promise.all([api("/api/elections"), api("/api/electoral-geography/regions"), api("/api/electoral-geography/summary")]).then(([e,g,s]) => { const list = e.elections || []; setElections(list); if (list[0]?._id) setElectionId(String(list[0]._id)); setRegions(g.data || []); setNationalStationCount(Number(s.data?.pollingStations || 0)); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { setConstituencies([]); setStations([]); setConstituencyId("all"); setStationId("all"); setRegionStationCount(0); if (regionId === "all") { setFocus({ center: GHANA, zoom: 6 }); return; } const load = async () => { try { const [c,s,r] = await Promise.all([api(`/api/electoral-geography/regions/${encodeURIComponent(regionId)}/constituencies`), api(`/api/electoral-geography/polling-stations?regionId=${encodeURIComponent(regionId)}`), api(`/api/electoral-geography/regions/${encodeURIComponent(regionId)}/constituencies`)]); setConstituencies(c.data || []); setStations(s.data || []); setRegionStationCount((s.data || []).length); const item = regions.find(x => String(x._id) === regionId); const p = coords(item) || await geocode(item?.name || ""); if (p) setFocus({ center: p, zoom: 8 }); } catch(e) { setError(e.message); } }; load(); }, [regionId]);
  useEffect(() => { setStationId("all"); if (constituencyId === "all") return; const load = async () => { try { const j = await api(`/api/electoral-geography/constituencies/${encodeURIComponent(constituencyId)}/polling-stations`); setStations(j.data || []); const item = constituencies.find(x => String(x._id) === constituencyId); const p = coords(item) || await geocode(item?.name || ""); if (p) setFocus({ center: p, zoom: 11 }); } catch(e) { setError(e.message); } }; load(); }, [constituencyId]);
  useEffect(() => { if (!electionId) return; setLoading(true); api(`/api/results/election/${encodeURIComponent(electionId)}`).then(j => setResults(j.results || [])).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [electionId]);

  const selectedRegion = useMemo(() => regions.find(r => String(r._id) === regionId), [regions, regionId]);
  const selectedConstituency = useMemo(() => constituencies.find(c => String(c._id) === constituencyId), [constituencies, constituencyId]);
  const selectedStation = useMemo(() => stations.find(s => String(s._id) === stationId), [stations, stationId]);
  const filtered = useMemo(() => results.filter(r => (regionId === "all" || String(r.regionId?._id || r.regionId) === regionId) && (constituencyId === "all" || String(r.constituencyId?._id || r.constituencyId) === constituencyId) && (stationId === "all" || String(r.pollingStationId?._id || r.pollingStationId) === stationId)), [results, regionId, constituencyId, stationId]);
  const validVotes = filtered.reduce((n,r) => n + Number(r.manualTotals?.totalValidVotes || 0), 0);
  const submitted = filtered.length;
  const constituencyCount = constituencyId === "all" ? 0 : stations.length;
  const currentRegionCount = regionId === "all" ? 0 : (constituencyId === "all" ? regionStationCount : regionStationCount);
  const nationalValid = results.reduce((n,r) => n + Number(r.manualTotals?.totalValidVotes || 0), 0);
  const selectStation = async (value) => { setStationId(value); const item = stations.find(s => String(s._id) === value); const p = coords(item) || await geocode(item?.name || ""); if (p) setFocus({ center: p, zoom: 14 }); };

  return <section className="results-map-explorer">
    <header><div><span>RESULTS GEOGRAPHY</span><h2>{title}</h2><p>Explore election results on the same responsive Ghana map at National, Regional, Constituency and Polling Station level.</p></div></header>
    {error && <div className="error">{error}</div>}
    <div className="filters">
      <label>Election<select value={electionId} onChange={e => setElectionId(e.target.value)}><option value="">Select election</option>{elections.map(e => <option key={e._id} value={e._id}>{e.name} • {e.year} • {e.type}</option>)}</select></label>
      <label>Geographic level<select value={regionId} onChange={e => setRegionId(e.target.value)}><option value="all">National — Ghana</option>{regions.map(r => <option key={r._id} value={r._id}>Regional — {r.name}</option>)}</select></label>
      <label>Constituency<select value={constituencyId} disabled={regionId === "all"} onChange={e => setConstituencyId(e.target.value)}><option value="all">All constituencies</option>{constituencies.map(c => <option key={c._id} value={c._id}>{c.name}{c.constituencyNumber ? ` • ${c.constituencyNumber}` : ""}</option>)}</select></label>
      <label>Polling station<select value={stationId} disabled={constituencyId === "all"} onChange={e => selectStation(e.target.value)}><option value="all">All polling stations</option>{stations.map(s => <option key={s._id} value={s._id}>{s.pollingStationCode} • {s.name}</option>)}</select></label>
    </div>
    <div className="map-wrap"><Map center={focus.center} zoom={focus.zoom} scrollWheelZoom className="map"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Recenter center={focus.center} zoom={focus.zoom}/>{selectedRegion && <CircleMarker center={coords(selectedRegion) || GHANA} radius={18}><Popup><b>{selectedRegion.name}</b><br/>Polling stations: {currentRegionCount.toLocaleString()}</Popup></CircleMarker>}{selectedConstituency && <CircleMarker center={coords(selectedConstituency) || GHANA} radius={13}><Popup><b>{selectedConstituency.name}</b><br/>Polling stations: {constituencyCount.toLocaleString()}</Popup></CircleMarker>}{selectedStation && coords(selectedStation) && <Marker position={coords(selectedStation)}><Popup><b>{selectedStation.name}</b><br/>{selectedStation.pollingStationCode || "No EC code"}<br/>Valid votes: {filtered.reduce((n,r)=>n+Number(r.manualTotals?.totalValidVotes||0),0).toLocaleString()}</Popup></Marker>}</Map></div>
    <div className="stats"><Stat label="National polling stations" value={nationalStationCount}/><Stat label="Selected region stations" value={regionId === "all" ? "—" : currentRegionCount}/><Stat label="Selected constituency stations" value={constituencyId === "all" ? "—" : constituencyCount}/><Stat label="Submitted result stations" value={submitted}/><Stat label="Valid votes" value={validVotes}/></div>
    <div className="summary"><div><b>National</b><span>{nationalStationCount.toLocaleString()} polling stations • {nationalValid.toLocaleString()} valid votes</span></div>{selectedRegion && <div><b>{selectedRegion.name}</b><span>{currentRegionCount.toLocaleString()} polling stations</span></div>}{selectedConstituency && <div><b>{selectedConstituency.name}</b><span>{constituencyCount.toLocaleString()} polling stations</span></div>}{selectedStation && <div><b>{selectedStation.name}</b><span>{selectedStation.pollingStationCode || "No EC code"}</span></div>}</div>
    {loading && <div className="loading">Loading election results…</div>}
    <style jsx>{`.results-map-explorer{padding:16px;border-radius:16px;background:#fff;border:1px solid #dce6df;color:#193127}.head,.results-map-explorer header{display:flex;justify-content:space-between}.results-map-explorer header span{color:#c9a227;font-size:9px;font-weight:900;letter-spacing:1.4px}.results-map-explorer h2{margin:4px 0;color:#075f2b;font-size:22px}.results-map-explorer header p{margin:0;color:#6f7c74;font-size:11px}.filters{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:14px 0}.filters label{display:grid;gap:5px;color:#647168;font-size:9px;font-weight:800}.filters select{width:100%;min-height:40px;border:1px solid #d6e1d9;border-radius:9px;background:#fff;color:#173d28;padding:0 8px;font-size:10px}.map-wrap{height:480px;border-radius:14px;overflow:hidden;border:1px solid #dce6df}.map{height:100%;width:100%}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:10px}.stats>div{padding:11px;border:1px solid #e0e7e2;border-radius:11px;background:#f9fbfa}.stats small{display:block;color:#77847c;font-size:8px}.stats strong{display:block;margin-top:4px;color:#075f2b;font-size:18px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:10px}.summary>div{padding:11px;border-radius:11px;background:#f3f7f4;border-left:3px solid #c9a227}.summary b{display:block;color:#075f2b;font-size:10px}.summary span{display:block;margin-top:4px;color:#68756d;font-size:9px}.error,.loading{padding:10px;margin-top:10px;border-radius:10px;font-size:10px}.error{background:#fff5f5;border:1px solid #edcaca;color:#a00000}.loading{background:#f7faf8;color:#647168}@media(max-width:850px){.filters{grid-template-columns:repeat(2,1fr)}.stats{grid-template-columns:repeat(3,1fr)}.summary{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.filters,.stats,.summary{grid-template-columns:1fr}.map-wrap{height:380px}}`}</style>
  </section>;
}
function Stat({label,value}){return <div><small>{label}</small><strong>{typeof value === "number" ? value.toLocaleString() : value}</strong></div>;}
