"use client";
import { useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import "leaflet/dist/leaflet.css";
const Map=dynamic(()=>import("react-leaflet").then(m=>m.MapContainer),{ssr:false});
const TileLayer=dynamic(()=>import("react-leaflet").then(m=>m.TileLayer),{ssr:false});
const Marker=dynamic(()=>import("react-leaflet").then(m=>m.Marker),{ssr:false});
const Popup=dynamic(()=>import("react-leaflet").then(m=>m.Popup),{ssr:false});
const CircleMarker=dynamic(()=>import("react-leaflet").then(m=>m.CircleMarker),{ssr:false});
const Recenter=dynamic(()=>import("./ResultsMapRecenter"),{ssr:false});
const GHANA=[7.9465,-1.0232];
const getToken=()=>typeof window==="undefined"?"":localStorage.getItem("polisync_token")||sessionStorage.getItem("polisync_token")||localStorage.getItem("token")||sessionStorage.getItem("token")||"";
async function api(path){const t=getToken();const r=await fetch(path,{cache:"no-store",headers:{Accept:"application/json",...(t?{Authorization:`Bearer ${t}`}:{})}});const j=await r.json().catch(()=>({}));if(!r.ok||j.success!==true)throw new Error(j.message||`Request failed (${r.status})`);return j;}
const coords=x=>{if(!x)return null;const lat=Number(x.latitude??x.lat??x.location?.latitude),lon=Number(x.longitude??x.lon??x.lng??x.location?.longitude);return Number.isFinite(lat)&&Number.isFinite(lon)?[lat,lon]:null;};
const fmt=n=>Number(n||0).toLocaleString();
export default function ElectionResultsMapExplorer({title="Election Results"}){
 const[elections,setElections]=useState([]),[electionId,setElectionId]=useState(""),[regions,setRegions]=useState([]),[constituencies,setConstituencies]=useState([]),[stations,setStations]=useState([]),[regionId,setRegionId]=useState("all"),[constituencyId,setConstituencyId]=useState("all"),[stationId,setStationId]=useState("all"),[data,setData]=useState(null),[focus,setFocus]=useState({center:GHANA,zoom:6}),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{Promise.all([api("/api/elections"),api("/api/electoral-geography/regions")]).then(([e,g])=>{const es=e.elections||[];setElections(es);if(es[0]?._id)setElectionId(String(es[0]._id));setRegions(g.data||[]);}).catch(e=>setError(e.message));},[]);
 useEffect(()=>{setConstituencies([]);setStations([]);setConstituencyId("all");setStationId("all");if(regionId==="all"){setFocus({center:GHANA,zoom:6});return;}api(`/api/electoral-geography/regions/${encodeURIComponent(regionId)}/constituencies`).then(j=>setConstituencies(j.data||[])).catch(e=>setError(e.message));api(`/api/electoral-geography/polling-stations?regionId=${encodeURIComponent(regionId)}`).then(j=>setStations(j.data||[])).catch(e=>setError(e.message));const r=regions.find(x=>String(x._id)===regionId);const p=coords(r);if(p)setFocus({center:p,zoom:8});},[regionId,regions]);
 useEffect(()=>{setStationId("all");if(constituencyId==="all")return;api(`/api/electoral-geography/constituencies/${encodeURIComponent(constituencyId)}/polling-stations`).then(j=>setStations(j.data||[])).catch(e=>setError(e.message));const c=constituencies.find(x=>String(x._id)===constituencyId);const p=coords(c);if(p)setFocus({center:p,zoom:11});},[constituencyId,constituencies]);
 useEffect(()=>{if(!electionId)return;setLoading(true);const view=stationId!=="all"?"polling_station":constituencyId!=="all"?"constituency":regionId!=="all"?"regional":"national";api(`/api/results/dashboard?${new URLSearchParams({view,electionId,regionId,constituencyId,pollingStationId:stationId})}`).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[electionId,regionId,constituencyId,stationId]);
 const selectedRegion=regions.find(r=>String(r._id)===regionId),selectedConstituency=constituencies.find(c=>String(c._id)===constituencyId),selectedStation=stations.find(s=>String(s._id)===stationId),coverage=data?.coverage||{national:{},regions:[],constituencies:[]};
 const rc=coverage.regions?.find(r=>String(r._id)===regionId),cc=coverage.constituencies?.find(c=>String(c._id)===constituencyId),election=elections.find(e=>String(e._id)===String(electionId));
 const filteredResults=useMemo(()=>{const rs=data?.pollingStation||[];return rs;},[data]);
 const partyRows=data?.presidentialSummary||[],seats=data?.parliamentarySummary?.seatsByParty||{};
 const partyMeta=new Map((election?.parties||[]).map(p=>[p.name,p]));
 return <section className="results-map-explorer"><header><span>RESULTS GEOGRAPHY</span><h2>{title}</h2><p>Explore National → Region → Constituency → Polling Station with live electoral coverage and result summaries.</p></header>{error&&<div className="error">{error}</div>}
 <div className="filters"><label>Election<select value={electionId} onChange={e=>setElectionId(e.target.value)}><option value="">Select election</option>{elections.map(e=><option key={e._id} value={e._id}>{e.name} • {e.year} • {e.type}</option>)}</select></label><label>Region<select value={regionId} onChange={e=>setRegionId(e.target.value)}><option value="all">National — Ghana</option>{regions.map(r=><option key={r._id} value={r._id}>Regional — {r.name}</option>)}</select></label><label>Constituency<select value={constituencyId} disabled={regionId==="all"} onChange={e=>setConstituencyId(e.target.value)}><option value="all">All constituencies</option>{constituencies.map(c=><option key={c._id} value={c._id}>{c.name}{c.constituencyNumber?` • ${c.constituencyNumber}`:""}</option>)}</select></label><label>Polling station<select value={stationId} disabled={constituencyId==="all"} onChange={e=>{setStationId(e.target.value);const s=stations.find(x=>String(x._id)===e.target.value);const p=coords(s);if(p)setFocus({center:p,zoom:15});}}><option value="all">All polling stations</option>{stations.map(s=><option key={s._id} value={s._id}>{s.pollingStationCode} • {s.name}</option>)}</select></label></div>
 <div className="map-wrap"><Map center={focus.center} zoom={focus.zoom} scrollWheelZoom className="map"><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Recenter center={focus.center} zoom={focus.zoom}/>{selectedRegion&&<CircleMarker center={coords(selectedRegion)||GHANA} radius={18}><Popup><b>{selectedRegion.name}</b><br/>Stations: {fmt(rc?.totalPollingStations)}<br/>Received: {fmt(rc?.received)}<br/>Pending: {fmt(rc?.awaitingPending)}</Popup></CircleMarker>}{selectedConstituency&&<CircleMarker center={coords(selectedConstituency)||GHANA} radius={13}><Popup><b>{selectedConstituency.name}</b><br/>Stations: {fmt(cc?.totalPollingStations)}<br/>Received: {fmt(cc?.received)}<br/>Pending: {fmt(cc?.awaitingPending)}</Popup></CircleMarker>}{selectedStation&&coords(selectedStation)&&<Marker position={coords(selectedStation)}><Popup><b>{selectedStation.name}</b><br/>{selectedStation.pollingStationCode||"No EC code"}</Popup></Marker>}</Map></div>
 <div className="coverage"><Coverage title="National" c={coverage.national}/>{selectedRegion&&<Coverage title={selectedRegion.name} c={rc}/>} {selectedConstituency&&<Coverage title={selectedConstituency.name} c={cc}/>}</div>
 {election?.type==="Presidential"&&<section className="result-card"><h3>Presidential Results Summary</h3><div className="levels"><Level label="Total Polling Stations" total={coverage.national?.totalPollingStations} received={coverage.national?.received} pending={coverage.national?.awaitingPending}/><Level label="Total Constituencies" total={coverage.national?.totalConstituencies} received={coverage.national?.receivedConstituencies} pending={coverage.national?.awaitingPendingConstituencies}/><Level label="Total Regions" total={coverage.national?.totalRegions} received={coverage.national?.receivedRegions} pending={coverage.national?.awaitingPendingRegions}/></div><div className="party-list">{partyRows.map(p=><div className="party" key={p.party}>{partyMeta.get(p.party)?.logoUrl?<img src={partyMeta.get(p.party).logoUrl} alt=""/>:<div className="logo">{p.party.slice(0,2)}</div>}<div><b>{p.party}</b><small>{fmt(p.votes)} votes</small></div><strong>{p.percentage}%</strong></div>)}</div></section>}
 {election?.type==="Parliamentary"&&<section className="result-card"><h3>Parliamentary Results</h3><p className="muted">Constituency winners by party across the selected election.</p><div className="party-seats">{Object.entries(seats).sort((a,b)=>b[1]-a[1]).map(([p,v])=><div key={p}><b>{p}</b><strong>{fmt(v)}</strong><small>constituency seats</small></div>)}</div></section>}
 {election?.type==="Presidential"&&selectedRegion&&<section className="result-card"><h3>{selectedRegion.name} Presidential Results</h3><div className="levels"><Level label="Constituencies" total={rc?.totalConstituencies} received={rc?.receivedConstituencies} pending={rc?.awaitingPendingConstituencies}/><Level label="Polling Stations" total={rc?.totalPollingStations} received={rc?.received} pending={rc?.awaitingPending}/></div></section>}
 {election?.type==="Presidential"&&selectedConstituency&&<section className="result-card"><h3>{selectedConstituency.name} Presidential Results</h3><div className="levels"><Level label="Polling Stations" total={cc?.totalPollingStations} received={cc?.received} pending={cc?.awaitingPending}/></div></section>}
 {loading&&<div className="loading">Loading election results…</div>}
 <style jsx>{`.results-map-explorer{padding:16px;border-radius:16px;background:#fff;border:1px solid #dce6df;color:#193127}.results-map-explorer header span{color:#c9a227;font-size:9px;font-weight:900;letter-spacing:1.4px}.results-map-explorer h2{margin:4px 0;color:#075f2b;font-size:22px}.results-map-explorer header p{margin:0;color:#6f7c74;font-size:11px}.filters{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:14px 0}.filters label{display:grid;gap:5px;color:#647168;font-size:9px;font-weight:800}.filters select{min-height:40px;border:1px solid #d6e1d9;border-radius:9px;background:#fff;color:#173d28;padding:0 8px;font-size:10px}.map-wrap{height:480px;border-radius:14px;overflow:hidden;border:1px solid #dce6df}.map{height:100%;width:100%}.coverage{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.coverage-card,.result-card{border:1px solid #e0e7e2;border-radius:12px;padding:12px;background:#f9fbfa}.coverage-card h4{margin:0 0 7px;color:#075f2b;font-size:11px}.coverage-card p{margin:4px 0;color:#6d7a72;font-size:9px}.coverage-card b{color:#173d28}.result-card{margin-top:10px;background:#fff}.result-card h3{margin:0 0 10px;color:#075f2b;font-size:15px}.muted{font-size:9px;color:#7b8780}.levels{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.level{padding:10px;border-radius:10px;background:#f3f7f4}.level b{display:block;color:#075f2b;font-size:10px}.level strong{display:block;margin-top:4px;font-size:17px}.level small{display:block;color:#77847c;font-size:8px;margin-top:3px}.party-list{display:grid;gap:7px;margin-top:10px}.party{display:flex;align-items:center;gap:9px;padding:9px;border-bottom:1px solid #edf1ee}.party img{width:32px;height:32px;object-fit:contain;border-radius:50%}.logo{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:#075f2b;color:#fff;font-size:9px;font-weight:900}.party div:nth-child(2){flex:1}.party b,.party small{display:block}.party small{color:#7b8780;font-size:9px;margin-top:2px}.party>strong{color:#075f2b}.party-seats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.party-seats>div{padding:12px;border-radius:10px;background:#f3f7f4}.party-seats b,.party-seats strong,.party-seats small{display:block}.party-seats strong{font-size:24px;color:#075f2b;margin-top:3px}.party-seats small{font-size:8px;color:#7b8780}.error{margin:10px 0;padding:10px;border-radius:9px;background:#fff5f5;border:1px solid #edcaca;color:#a00000;font-size:10px}.loading{padding:10px;margin-top:10px;text-align:center;color:#647168;font-size:9px}@media(max-width:850px){.filters{grid-template-columns:repeat(2,1fr)}.coverage{grid-template-columns:1fr 1fr}.levels{grid-template-columns:1fr 1fr}.party-seats{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.filters,.coverage,.levels,.party-seats{grid-template-columns:1fr}.map-wrap{height:380px}}`}</style></section>;
}
function Coverage({title,c={}}){return <div className="coverage-card"><h4>{title}</h4><p><b>{fmt(c?.totalPollingStations)}</b> total polling stations</p><p>Received <b>{fmt(c?.received)}</b> • Awaiting/Pending <b>{fmt(c?.awaitingPending)}</b></p>{c?.totalConstituencies!==undefined&&<p><b>{fmt(c.totalConstituencies)}</b> constituencies • {fmt(c.receivedConstituencies)} received • {fmt(c.awaitingPendingConstituencies)} pending</p>}</div>}
function Level({label,total,received,pending}){return <div className="level"><b>{label}</b><strong>{fmt(total)}</strong><small>Received: {fmt(received)} • Awaiting/Pending: {fmt(pending)}</small></div>}
