"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import DashboardShell from "./DashboardShell";

const API_URL = (process.env.NEXT_PUBLIC_API_URL || "").replace(/\/+$/, "");
const getToken = () => typeof window === "undefined" ? "" : localStorage.getItem("polisync_token") || sessionStorage.getItem("polisync_token") || localStorage.getItem("token") || sessionStorage.getItem("token") || localStorage.getItem("authToken") || sessionStorage.getItem("authToken") || localStorage.getItem("accessToken") || sessionStorage.getItem("accessToken") || "";
const MODULE_ENDPOINTS = { security:"/api/health", notifications:"/api/notifications", announcements:"/api/announcements", elections:"/api/elections", "polling-stations":"/api/electoral-geography/polling-stations", approvals:"/api/platform-users" };

export default function PlatformModulePage({ title, subtitle, activeSection, description, endpoint }) {
  const [data,setData]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const resolvedEndpoint=endpoint || MODULE_ENDPOINTS[activeSection] || "";
  const load=useCallback(async()=>{if(!resolvedEndpoint){setLoading(false);return;}setLoading(true);setError("");try{const token=getToken();const r=await fetch(`${API_URL}${resolvedEndpoint}`,{cache:"no-store",headers:{Accept:"application/json",...(token?{Authorization:`Bearer ${token}`}:{})}});const p=await r.json().catch(()=>({}));if(!r.ok||p.success===false)throw Object.assign(new Error(p.message||`Unable to load ${title}.`),{code:p.code});setData(p);}catch(e){setError(e.code==="SESSION_EXPIRED"?"Your security session has expired. Please log in again and complete phone verification.":e.message||`Unable to load ${title}.`);}finally{setLoading(false);}},[resolvedEndpoint,title]);
  useEffect(()=>{load();},[load]);
  const items=useMemo(()=>{if(Array.isArray(data?.elections))return data.elections;if(Array.isArray(data?.data))return data.data;if(Array.isArray(data?.users))return data.users;if(Array.isArray(data?.notifications))return data.notifications;if(Array.isArray(data?.items))return data.items;if(Array.isArray(data?.announcements))return data.announcements;return[];},[data]);
  const render=()=>{if(loading)return <div className="state">Loading live data…</div>;if(error)return <div className="state error">{error}</div>;if(activeSection==="security")return <section className="grid"><Item label="Platform" value={data?.platform||"POLISYNC AFRICA"}/><Item label="Status" value={data?.status||"Unknown"}/><Item label="Version" value={data?.version||"—"}/><Item label="Uptime" value={typeof data?.uptime==="number"?`${Math.floor(data.uptime/60)} min`:"—"}/></section>;if(items.length===0)return <div className="state">No live records are available yet.</div>;return <section className="list">{items.slice(0,100).map((item,i)=><article className="item-card" key={item._id||item.id||i}><span className="status">{item.status||item.accountStatus||item.type||"Live"}</span><h3>{item.name||item.title||item.subject||item.displayName||item.pollingStationCode||"Record"}</h3><p>{item.description||item.body||item.message||item.email||item.district||item.type||""}</p>{(item.year||item.organizationType||item.role)&&<small>{[item.year,item.organizationType,item.role].filter(Boolean).join(" • ")}</small>}</article>)}</section>;};
  return <DashboardShell role="super_admin" title={title} subtitle={subtitle} activeSection={activeSection}><main className="page"><header><div><span>POLISYNC AFRICA • SUPER ADMIN</span><h2>{title}</h2><p>{description||subtitle}</p></div><button onClick={load} disabled={loading}>{loading?"Loading…":"↻ Refresh"}</button></header><section className="workspace">{render()}</section></main><style jsx>{styles}</style></DashboardShell>;
}
function Item({label,value}){return <div className="stat"><span>{label}</span><strong>{String(value)}</strong></div>}
const styles=`.page{min-height:100%;padding:clamp(14px,2.5vw,32px);background:#f5f8f6;color:#26332b;box-sizing:border-box}.page>header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.page>header span{color:#c9a227;font-size:9px;font-weight:900;letter-spacing:1.4px}.page h2{margin:6px 0;color:#075f2b;font-size:30px}.page p{margin:0;color:#6f7c74;font-size:11px}.page>header button{border:0;border-radius:9px;background:#075f2b;color:#fff;padding:10px 13px;font-size:10px;font-weight:800}.workspace{margin-top:16px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.stat{padding:16px;border:1px solid #d4af37;border-radius:13px;background:#fff}.stat span{display:block;color:#7b8780;font-size:9px}.stat strong{display:block;margin-top:5px;color:#075f2b;font-size:20px}.list{display:grid;gap:10px}.item-card{padding:17px;border:1px solid #d4af37;border-radius:14px;background:#fff}.item-card h3{margin:6px 0;color:#075f2b;font-size:16px}.item-card p{color:#4f5d55;font-size:11px}.item-card small{color:#87928b;font-size:8px}.status{display:inline-block;padding:5px 8px;border-radius:999px;background:#eaf6ee;color:#075f2b;font-size:8px;font-weight:900}.state{padding:24px;border:1px solid #d4af37;border-radius:13px;background:#fff;text-align:center;color:#66736b;font-size:11px}.error{background:#fff5f5;border-color:#edcaca;color:#a00000}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}.page>header{display:block}}@media(max-width:520px){.grid{grid-template-columns:1fr}}`;