"use client";

import { useEffect, useMemo, useState } from "react";
import DashboardShell from "../../../../components/dashboard/DashboardShell";
import superAdminNavigation from "../../../../components/dashboard/superAdminNavigation";

const API = (process.env.NEXT_PUBLIC_API_URL || "https://polisync-platform-1.onrender.com").replace(/\/+$/, "");
const auth = () => { if (typeof window === "undefined") return {}; const t = localStorage.getItem("polisync_token") || sessionStorage.getItem("polisync_token") || localStorage.getItem("authToken") || sessionStorage.getItem("authToken"); return t ? { Authorization: `Bearer ${t}` } : {}; };
async function api(path, options = {}) { const r = await fetch(`${API}${path}`, { cache: "no-store", ...options, headers: { Accept: "application/json", "Content-Type": "application/json", ...auth(), ...(options.headers || {}) } }); const b = await r.json().catch(() => ({})); if (!r.ok || b.success === false) throw new Error(b.message || `Request failed (${r.status})`); return b; }

export default function PresidentialCandidatesPage() {
  const [elections, setElections] = useState([]), [parties, setParties] = useState([]), [selectedId, setSelectedId] = useState(""), [candidates, setCandidates] = useState([]), [newParty, setNewParty] = useState({ name: "", logoUrl: "" }), [saving, setSaving] = useState(false), [message, setMessage] = useState(""), [error, setError] = useState("");
  const election = useMemo(() => elections.find((e) => String(e._id) === String(selectedId)), [elections, selectedId]);

  const load = async () => { setError(""); try { const [e, p] = await Promise.all([api("/api/elections"), api("/api/elections/parties")]); const list = (e.elections || []).filter((x) => x.type === "Presidential"); setElections(list); setParties(p.parties || []); setSelectedId((current) => current || String(list[0]?._id || "")); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { const e = elections.find((x) => String(x._id) === String(selectedId)); setCandidates((e?.candidates || []).map((c) => ({ ...c, partyId: c.partyId || parties.find((p) => p.name.toLowerCase() === String(c.party || "").toLowerCase())?.id || null }))); }, [selectedId, elections, parties]);

  const addCandidate = (partyId = null) => { const p = parties.find((x) => String(x.id) === String(partyId)); setCandidates((x) => [...x, { name: "", partyId: p?.id || null, party: p?.name || "Independent", partyLogoUrl: p?.logoUrl || "", profilePictureUrl: "", constituencyId: null }]); };
  const update = (i, key, value) => setCandidates((x) => x.map((c, n) => n === i ? { ...c, [key]: value } : c));
  const assign = (i, partyId) => { const p = parties.find((x) => String(x.id) === String(partyId)); update(i, "partyId", p?.id || null); update(i, "party", p?.name || "Independent"); update(i, "partyLogoUrl", p?.logoUrl || ""); };
  const save = async () => { if (!election) return; setSaving(true); setError(""); setMessage(""); try { const missing = parties.filter((p) => !candidates.some((c) => String(c.partyId) === String(p.id) && c.name.trim())); if (missing.length) throw new Error(`Add a presidential candidate for: ${missing.map((p) => p.name).join(", ")}.`); if (!candidates.some((c) => !c.partyId && c.name.trim())) throw new Error("Add the Independent presidential candidate too."); const result = await api(`/api/elections/${election._id}`, { method: "PATCH", body: JSON.stringify({ candidates: candidates.map((c) => ({ name: c.name, partyId: c.partyId || null, party: c.party || "Independent", partyLogoUrl: c.partyLogoUrl || "", profilePictureUrl: c.profilePictureUrl || "", constituencyId: c.constituencyId || null })) }) }); setElections((x) => x.map((e) => e._id === result.election._id ? result.election : e)); setMessage("Presidential candidates saved successfully."); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const addParty = async (e) => { e.preventDefault(); setError(""); setMessage(""); try { if (!newParty.name.trim()) throw new Error("Enter the new political party name."); const result = await api("/api/elections/parties", { method: "POST", body: JSON.stringify(newParty) }); setParties((x) => [...x, result.party]); setNewParty({ name: "", logoUrl: "" }); setMessage("New political party added to the system and synchronized to elections."); await load(); } catch (err) { setError(err.message); } };

  return <DashboardShell role="super_admin" navigation={superAdminNavigation} activeSection="elections" title="Presidential Candidates" subtitle="Assign every participating party a presidential candidate, including Independent">
    <main className="page">
      {message && <div className="notice ok">✓ {message}</div>}{error && <div className="notice err">{error}</div>}
      <section className="card"><div className="head"><div><h2>Election Presidential Candidates</h2><p>Every participating political party must have exactly one presidential candidate. Independent is always handled separately.</p></div><button onClick={load}>↻ Refresh</button></div>
        <label className="select">Election<select value={selectedId} onChange={(e) => setSelectedId(e.target.value)}><option value="">Select a Presidential election</option>{elections.map((e) => <option key={e._id} value={e._id}>{e.name} — {e.year}</option>)}</select></label>
        {election && <div className="grid">{parties.map((p) => { const index = candidates.findIndex((c) => String(c.partyId) === String(p.id)); const c = index >= 0 ? candidates[index] : null; return <article className="candidate-card" key={p.id}><div className="party"><div className="logo">{p.logoUrl ? <img src={p.logoUrl} alt="" /> : p.name.slice(0, 2)}</div><div><b>{p.name}</b><small>Political party</small></div></div>{c ? <><input value={c.name} onChange={(e) => update(index, "name", e.target.value)} placeholder={`${p.name} presidential candidate`} /><input value={c.profilePictureUrl || ""} onChange={(e) => update(index, "profilePictureUrl", e.target.value)} placeholder="Candidate profile picture URL" /><button className="remove" onClick={() => setCandidates((x) => x.filter((_, n) => n !== index))}>Remove candidate</button></> : <button className="add" onClick={() => addCandidate(p.id)}>+ Add {p.name} presidential candidate</button>}</article>; })}
          <article className="candidate-card independent"><div className="party"><div className="logo">IN</div><div><b>Independent</b><small>Presidential candidate</small></div></div>{(() => { const index = candidates.findIndex((c) => !c.partyId); const c = index >= 0 ? candidates[index] : null; return c ? <><input value={c.name} onChange={(e) => update(index, "name", e.target.value)} placeholder="Independent presidential candidate" /><input value={c.profilePictureUrl || ""} onChange={(e) => update(index, "profilePictureUrl", e.target.value)} placeholder="Candidate profile picture URL" /><button className="remove" onClick={() => setCandidates((x) => x.filter((_, n) => n !== index))}>Remove candidate</button></> : <button className="add" onClick={() => addCandidate(null)}>+ Add Independent presidential candidate</button>; })()}</article>
        </div>}
        {election && <button className="save" disabled={saving} onClick={save}>{saving ? "Saving…" : "Save Presidential Candidates"}</button>}
      </section>

      <section className="card"><div className="head"><div><h2>System Political Parties</h2><p>Super Admin can add a new political party in the future. New approved parties become available for election participation and candidate association.</p></div></div><form className="new-party" onSubmit={addParty}><input value={newParty.name} onChange={(e) => setNewParty({ ...newParty, name: e.target.value })} placeholder="New political party name" /><input value={newParty.logoUrl} onChange={(e) => setNewParty({ ...newParty, logoUrl: e.target.value })} placeholder="Party logo URL (optional)" /><button className="save">+ Add Political Party</button></form><div className="party-list">{parties.map((p) => <div key={p.id} className="party-row"><span className="mini">{p.logoUrl ? <img src={p.logoUrl} alt="" /> : p.name.slice(0,2)}</span><b>{p.name}</b><small>Registered in PoliSync</small></div>)}</div></section>
    </main>
    <style jsx>{`.page{padding:20px;max-width:1200px;margin:auto;background:#f5f8f6;min-height:100%}.card{background:#fff;border:1px solid #dce6e0;border-radius:18px;padding:20px;margin-bottom:16px;box-shadow:0 8px 24px rgba(20,60,42,.05)}.head{display:flex;justify-content:space-between;gap:15px;align-items:flex-start}.head h2{margin:0;color:#075d2e}.head p{margin:5px 0 15px;color:#708078;line-height:1.5;font-size:13px}.head button,.add,.remove,.save{border:1px solid #cad8d0;border-radius:9px;padding:10px 13px;background:#fff;color:#174e35;font-weight:800;cursor:pointer}.select{display:grid;gap:7px;font-weight:800;color:#385746}.select select,.candidate-card input,.new-party input{width:100%;box-sizing:border-box;border:1px solid #d3dfd8;border-radius:9px;padding:11px;font-size:16px;background:#fbfdfc}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:15px}.candidate-card{border:1px solid #dbe6df;border-radius:13px;padding:13px;display:grid;gap:9px}.party{display:flex;gap:10px;align-items:center}.logo,.mini{width:46px;height:46px;border-radius:50%;background:#edf5ef;display:grid;place-items:center;overflow:hidden;font-weight:900;color:#31614a;font-size:11px}.logo img,.mini img{width:100%;height:100%;object-fit:contain}.party b{display:block;color:#174e35}.party small,.party-row small{display:block;color:#829088;font-size:10px}.add,.save{background:#075d2e;color:#fff;border-color:#075d2e}.remove{color:#a33b3b}.save{margin-top:15px}.new-party{display:grid;grid-template-columns:1fr 1fr auto;gap:9px}.party-list{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.party-row{border:1px solid #dbe6df;border-radius:10px;padding:9px;display:flex;gap:8px;align-items:center}.mini{width:32px;height:32px;flex:0 0 32px}.notice{padding:11px 13px;border-radius:10px;margin-bottom:12px;font-weight:800}.ok{background:#e8f7ee;color:#17623d}.err{background:#fff0f0;color:#9d3434}@media(max-width:800px){.grid,.party-list{grid-template-columns:1fr}.new-party{grid-template-columns:1fr}.head{display:block}.head button{margin-top:8px;width:100%}}`}</style>
  </DashboardShell>;
}
