"use client";

import { useEffect, useState } from "react";
import DashboardShell from "../../../../components/dashboard/DashboardShell";
import superAdminNavigation from "../../../../components/dashboard/superAdminNavigation";

const fmt = n => Number(n || 0).toLocaleString();
const getToken = () => typeof window === "undefined" ? "" : ["polisync_token","authToken","accessToken","token"].map(k => localStorage.getItem(k)||sessionStorage.getItem(k)).find(Boolean)||"";

export default function ReconciliationPage(){
  const [plan,setPlan]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const run=async()=>{setLoading(true);setError("");try{const t=getToken();const r=await fetch("/api/electoral-geography/integrity/reconciliation/preview",{cache:"no-store",headers:{Accept:"application/json",...(t?{Authorization:`Bearer ${t}`}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok||!b.success)throw new Error(b.message||"Reconciliation preview failed.");setPlan(b.data);}catch(e){setError(e.message||"Unable to build reconciliation preview.");}finally{setLoading(false);}};
  useEffect(()=>{run();},[]);
  return <DashboardShell role="super_admin" navigation={superAdminNavigation} activeSection="electoral-data" title="Electoral Reconciliation" subtitle="Safe dry-run before applying EC data changes">
    <main className="page"><div className="top"><div><a href="/super-admin/electoral-data-health">← Electoral Data Health</a><h1>EC Data Reconciliation</h1><p>This is a <b>dry run</b>. No electoral records are changed here. The source must pass validation before any future apply operation is allowed.</p></div><button onClick={run} disabled={loading}>{loading?"Analyzing…":"↻ Run Dry Run"}</button></div>
      {error&&<div className="error"><b>Source rejected</b><span>{error}</span><button onClick={run}>Retry</button></div>}
      {plan&&<><section className={`banner ${plan.safeToApply?"safe":"blocked"}`}><strong>{plan.safeToApply?"✓ Source passed safety checks":"! Apply blocked"}</strong><span>{plan.safeToApply?"No unresolved rows or source-missing active stations were detected in this preview.":"The source contains unresolved mappings or active database stations missing from the source. No changes should be applied."}</span></section>
      <section className="metrics"><Metric label="Source Rows" value={plan.summary.sourceRows}/><Metric label="New Stations" value={plan.summary.newStations}/><Metric label="Changed Stations" value={plan.summary.changedStations}/><Metric label="Unchanged" value={plan.summary.unchangedStations}/><Metric label="Missing From Source" value={plan.summary.missingActiveStations} warn/><Metric label="Unresolved Rows" value={plan.summary.unresolvedRows} warn/></section>
      <section className="grid"><Panel title="New Stations" items={plan.newStations} empty="No new stations."/><Panel title="Changed Stations" items={plan.changedStations} empty="No changed stations."/><Panel title="Active DB Stations Missing From Source" items={plan.sourceMissingActiveStations} empty="None detected."/><Panel title="Unresolved Source Rows" items={plan.unresolvedRows} empty="None detected."/></section>
      <div className="note"><b>Safety rule:</b> stations missing from the source are reported for review, never deleted or deactivated by this dry run.</div></>}
    </main><style jsx>{css}</style></DashboardShell>;
}
function Metric({label,value,warn}){return <article><strong className={warn&&Number(value)?"warn":""}>{fmt(value)}</strong><span>{label}</span></article>}
function Panel({title,items,empty}){return <section className="panel"><header><h2>{title}</h2><b>{fmt(items?.length)}</b></header>{items?.length?<div>{items.slice(0,100).map((x,i)=><div className="item" key={x.id||x._id||x.code||i}><strong>{x.code||x.name||"Record"}</strong><span>{x.region||x.reason||x.constituency||x.district||"Requires review"}</span></div>)}</div>:<p className="empty">✓ {empty}</p>}{items?.length>100&&<small>Showing 100 of {fmt(items.length)} records.</small>}</section>}
const css=`.page{padding:clamp(14px,2.5vw,30px);background:#f4f7f5;color:#203128;min-height:100%}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;padding:27px 29px;border-radius:20px;background:linear-gradient(115deg,#004d28,#006b38 60%,#073d26);color:#fff}.top a{color:#dceee4;text-decoration:none;font-size:11px;font-weight:800}.top h1{font-size:32px;margin:9px 0 6px}.top p{max-width:800px;color:rgba(255,255,255,.78);font-size:12px;line-height:1.6;margin:0}.top button{min-height:44px;padding:10px 16px;border:0;border-radius:10px;background:#fff;color:#075d31;font-weight:850;white-space:nowrap}.banner{display:flex;gap:10px;align-items:center;margin-top:14px;padding:14px 16px;border-radius:13px;font-size:11px}.banner.safe{background:#e8f6ed;border:1px solid #cce6d5;color:#08713a}.banner.blocked{background:#fff2df;border:1px solid #efd7ae;color:#955b08}.banner span{color:#586960}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:14px 0}.metrics article{padding:14px;border:1px solid #dbe6df;border-radius:13px;background:#fff}.metrics strong{display:block;font-size:23px;color:#075f2b}.metrics .warn{color:#a45d08}.metrics span{font-size:9px;color:#7d8a83;font-weight:800}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.panel{border:1px solid #dbe6df;border-radius:14px;background:#fff;overflow:hidden}.panel header{display:flex;justify-content:space-between;padding:14px 16px;border-bottom:1px solid #edf2ee;background:#f9fbfa}.panel h2{font-size:13px;margin:0;color:#075f2b}.panel header b{font-size:9px;background:#eef5f1;border-radius:6px;padding:5px 7px}.item{display:flex;justify-content:space-between;gap:12px;padding:10px 15px;border-bottom:1px solid #edf2ee;font-size:9px}.item strong{overflow-wrap:anywhere}.item span{color:#7c8982;text-align:right;max-width:60%}.empty{padding:18px 15px;color:#08713a;font-size:10px}.panel>small{display:block;padding:9px 15px;color:#9a7b25;font-size:9px}.note{margin-top:14px;padding:13px 15px;background:#fff;border:1px solid #dbe6df;border-radius:12px;color:#66756d;font-size:10px}.note b{color:#075f2b}.error{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:14px 0;padding:12px;border:1px solid #efc8c4;background:#fff4f3;color:#81352e;border-radius:11px;font-size:10px}.error span{flex:1}.error button{border:0;border-radius:7px;padding:7px 10px;background:#9d332b;color:#fff;font-weight:800}@media(max-width:900px){.top{align-items:flex-start;flex-direction:column}.top button{width:100%}.metrics{grid-template-columns:repeat(3,1fr)}}@media(max-width:600px){.metrics{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}.banner{align-items:flex-start;flex-direction:column}.top h1{font-size:25px}.item{display:block}.item span{display:block;text-align:left;margin-top:4px;max-width:none}}`;
