"use client";

import { useEffect, useState } from "react";
import DashboardShell from "../../../components/dashboard/DashboardShell";

const API = (process.env.NEXT_PUBLIC_API_URL || "https://polisync-platform-1.onrender.com").replace(/\/+$/, "");
function token(){if(typeof window === "undefined")return "";return ["polisync_token","authToken","accessToken","token","jwt"].map((key)=>localStorage.getItem(key)||sessionStorage.getItem(key)).find(Boolean)||"";}
async function request(path,options={}){const r=await fetch(`${API}${path}`,{cache:"no-store",...options,headers:{Accept:"application/json",...(options.body?{"Content-Type":"application/json"}:{}),Authorization:`Bearer ${token()}`}});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw Error(d.message||`Request failed (${r.status})`);return d;}
function readImage(file){return new Promise((resolve,reject)=>{if(!file)return resolve("");if(file.size>2*1024*1024)return reject(Error("Party logo is too large. Maximum size is 2 MB."));const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(Error("Unable to read the logo."));reader.readAsDataURL(file);});}

export default function PartyProfilePage(){
 const [form,setForm]=useState({name:"",email:"",phone:"",website:"",description:"",logo:""});
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{(async()=>{try{const d=await request("/api/party-organization/me/profile");const o=d.organization||{};setForm({name:o.politicalPartyName||o.name||"",email:o.email||"",phone:o.phone||"",website:o.website||"",description:o.description||"",logo:o.logo||""});}catch(e){setError(e.message)}finally{setLoading(false)}})()},[]);
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 const save=async(e)=>{e.preventDefault();setSaving(true);setError("");setNotice("");try{const d=await request("/api/party-organization/me/profile",{method:"PATCH",body:JSON.stringify({email:form.email,phone:form.phone,website:form.website,description:form.description,logo:form.logo})});setNotice(d.message||"Party information updated.");}catch(e){setError(e.message)}finally{setSaving(false)}};
 return <DashboardShell role="party" title="Organization Profile" subtitle="Manage your political party information and official identity"><main className="page"><header><span>PARTY ADMINISTRATION</span><h1>Organization Profile</h1><p>Update the information shown across PoliSync. Your party identity is controlled by the organization, while the Super Admin maintains the broader official election registry.</p></header>{loading?<div className="state">Loading party profile…</div>:<form className="card" onSubmit={save}>{notice&&<div className="notice success">✓ {notice}</div>}{error&&<div className="notice error">{error}</div>}<div className="identity"><div className="logo">{form.logo?<img src={form.logo} alt="Party logo"/>:<span>{form.name.slice(0,1)||"P"}</span>}</div><div><strong>{form.name||"Political Party"}</strong><small>Official party identity</small><label className="file">Change party logo<input type="file" accept="image/*" onChange={async(e)=>{try{const logo=await readImage(e.target.files?.[0]);if(logo)change("logo",logo)}catch(err){setError(err.message)}e.target.value=""}}/></label></div></div><div className="grid"><label>Party name<input value={form.name} disabled/></label><label>Email<input value={form.email} onChange={e=>change("email",e.target.value)} type="email" placeholder="party@example.com"/></label><label>Phone<input value={form.phone} onChange={e=>change("phone",e.target.value)} placeholder="+233XXXXXXXXX"/></label><label>Website<input value={form.website} onChange={e=>change("website",e.target.value)} placeholder="https://…"/></label></div><label>Description<textarea value={form.description} onChange={e=>change("description",e.target.value)} rows={5} placeholder="Official party description…"/></label><div className="actions"><span>Party candidate information can be maintained from <b>Candidates</b> in the party dashboard.</span><button disabled={saving}>{saving?"Saving…":"Save Party Information"}</button></div></form>}</main><style jsx>{styles}</style></DashboardShell>;
}
const styles=`.page{min-height:100%;padding:clamp(14px,2.5vw,32px);background:#f5f8f6;color:#26332b}.page>header span{color:#c9a227;font-size:9px;font-weight:900;letter-spacing:1.4px}.page h1{margin:6px 0;color:#075f2b;font-size:30px}.page>header p{max-width:820px;margin:0 0 16px;color:#6f7c74;font-size:12px;line-height:1.5}.card{max-width:980px;padding:20px;border:1px solid #dce6df;border-radius:15px;background:#fff}.notice{padding:10px 12px;border-radius:9px;margin-bottom:12px;font-size:10px;font-weight:800}.success{background:#eaf7ee;color:#08713a}.error{background:#fff1f1;color:#a00000}.identity{display:flex;gap:13px;align-items:center;padding-bottom:18px;border-bottom:1px solid #edf1ee;margin-bottom:16px}.logo{width:72px;height:72px;flex:0 0 72px;border-radius:12px;background:#edf5ef;display:grid;place-items:center;overflow:hidden;color:#075f2b;font-size:22px;font-weight:900}.logo img{width:100%;height:100%;object-fit:contain}.identity strong,.identity small{display:block}.identity strong{font-size:16px;color:#075f2b}.identity small{margin:3px 0 8px;color:#8a958e;font-size:8px}.file{display:flex;flex-direction:column;gap:5px;color:#53635a;font-size:9px;font-weight:800}.file input{font-size:9px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:11px}.card>label,.grid label{display:flex;flex-direction:column;gap:6px;color:#53635a;font-size:9px;font-weight:800}.grid input,.card textarea{box-sizing:border-box;border:1px solid #dce6df;border-radius:9px;background:#fbfcfb;padding:10px;font-size:11px;color:#26332b}.grid input{height:42px}.card>label{margin-top:11px}.actions{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:15px;padding-top:14px;border-top:1px solid #edf1ee}.actions span{font-size:9px;color:#7a8780}.actions button{border:0;border-radius:9px;background:#075f2b;color:#fff;padding:11px 14px;font-size:10px;font-weight:900}.actions button:disabled{opacity:.5}.state{padding:25px;background:#fff;border:1px solid #dce6df;border-radius:14px;color:#718078;text-align:center;font-size:10px}@media(max-width:700px){.grid{grid-template-columns:1fr}.actions{display:block}.actions button{width:100%;margin-top:10px}}
`;
