const mongoose = require("mongoose");

/*
|--------------------------------------------------------------------------
| Notification Schema
|--------------------------------------------------------------------------
| Stores in-app, email and SMS notifications generated by POLISYNC AFRICA.
|--------------------------------------------------------------------------
*/

const NotificationSchema = new mongoose.Schema(
  {
    /*
    |--------------------------------------------------------------------------
    | Recipient
    |--------------------------------------------------------------------------
    */

    recipient: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Related Calendar Event
    |--------------------------------------------------------------------------
    */

    event: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "CalendarEvent",
      default: null,
      index: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Notification Type
    |--------------------------------------------------------------------------
    */

    type: {
      type: String,
      enum: [
        "event_created",
        "event_updated",
        "event_cancelled",
        "event_reminder",
        "invitation",
        "invitation_accepted",
        "invitation_declined",
        "invitation_tentative",
        "attendee_added",
        "attendee_removed",
        "system",
        "other",
      ],
      default: "system",
      required: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Delivery Channel
    |--------------------------------------------------------------------------
    */

    channel: {
      type: String,
      enum: [
        "in_app",
        "email",
        "sms",
      ],
      default: "in_app",
      required: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Notification Title
    |--------------------------------------------------------------------------
    */

    title: {
      type: String,
      required: true,
      trim: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Notification Message
    |--------------------------------------------------------------------------
    */

    message: {
      type: String,
      required: true,
      trim: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Notification Status
    |--------------------------------------------------------------------------
    */

    status: {
      type: String,
      enum: [
        "pending",
        "sent",
        "delivered",
        "failed",
        "cancelled",
      ],
      default: "pending",
      index: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Scheduled Delivery Time
    |--------------------------------------------------------------------------
    */

    scheduledFor: {
      type: Date,
      default: null,
      index: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Sent Time
    |--------------------------------------------------------------------------
    */

    sentAt: {
      type: Date,
      default: null,
    },

    /*
    |--------------------------------------------------------------------------
    | Delivered Time
    |--------------------------------------------------------------------------
    */

    deliveredAt: {
      type: Date,
      default: null,
    },

    /*
    |--------------------------------------------------------------------------
    | Read Status
    |--------------------------------------------------------------------------
    */

    read: {
      type: Boolean,
      default: false,
      index: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Read Time
    |--------------------------------------------------------------------------
    */

    readAt: {
      type: Date,
      default: null,
    },

    /*
    |--------------------------------------------------------------------------
    | Error Information
    |--------------------------------------------------------------------------
    */

    errorMessage: {
      type: String,
      default: "",
      trim: true,
    },

    /*
    |--------------------------------------------------------------------------
    | Additional Data
    |--------------------------------------------------------------------------
    | Allows us to store useful information without changing the schema.
    |--------------------------------------------------------------------------
    */

    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    /*
    |--------------------------------------------------------------------------
    | Created By
    |--------------------------------------------------------------------------
    */

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true,
  }
);


/*
|--------------------------------------------------------------------------
| Indexes
|--------------------------------------------------------------------------
*/

/*
 * Quickly find unread notifications for a user.
 */
NotificationSchema.index({
  recipient: 1,
  read: 1,
  createdAt: -1,
});

/*
 * Quickly find pending notifications that are ready to be sent.
 */
NotificationSchema.index({
  status: 1,
  scheduledFor: 1,
});

/*
 * Quickly find notifications belonging to a calendar event.
 */
NotificationSchema.index({
  event: 1,
  createdAt: -1,
});


/*
|--------------------------------------------------------------------------
| Export Model
|--------------------------------------------------------------------------
*/

module.exports = mongoose.model(
  "Notification",
  NotificationSchema
);
