"use client";

import DashboardShell from "../../../../components/dashboard/DashboardShell";
import DashboardPager from "../../../../components/dashboard/DashboardPager";
import WeatherCard from "../../../../components/dashboard/WeatherCard";
import RemindersPanel from "../../../../components/dashboard/RemindersPanel";

const APPROVALS=[["Users","0","👥"],["Organizations","0","🏢"],["Polling Stations","0","📍"],["Candidates","0","👤"]];
const ACTIONS=[["📢","Announcement","/super-admin/announcements"],["👥","Manage Users","/super-admin/users"],["🏢","Organizations","/super-admin/organizations"],["📊","Generate Report","/super-admin/reports"],["🛡️","Security Center","/super-admin/security"],["⚙️","System Settings","/super-admin/settings"]];

export default function DashboardOperations(){return <DashboardShell role="super_admin" title="Dashboard Operations" subtitle="Approvals, actions, weather and daily workflow" activeSection="overview"><main className="page"><DashboardPager current="/super-admin/dashboard/operations"/><section className="hero"><span>SUPER ADMIN OPERATIONS</span><h2>Keep the platform moving.</h2><p>Operational tools now live on their own focused workspace instead of competing for attention on the overview.</p></section><section className="grid"><article className="panel approvals"><header><div className="icon">✓</div><div><small>01 • ATTENTION</small><h3>Pending Approvals</h3><p>Items requiring administrative review.</p></div></header><div className="approval-grid">{APPROVALS.map(([label,value,icon])=><div className="approval" key={label}><span>{icon}</span><strong>{value}</strong><small>{label}</small></div>)}</div></article><article className="panel"><header><div className="icon">ϟ</div><div><small>02 • ACTIONS</small><h3>Quick Actions</h3></div></header><div className="actions">{ACTIONS.map(([icon,label,href])=><a href={href} key={label}><span>{icon}</span><strong>{label}</strong><i>→</i></a>)}</div></article><article className="panel"><header><div className="icon">☁</div><div><small>03 • ENVIRONMENT</small><h3>Weather</h3></div></header><WeatherCard/></article><article className="panel"><header><div className="icon">◷</div><div><small>04 • DAILY FLOW</small><h3>Reminders</h3></div></header><RemindersPanel initialReminders={[]}/></article></section></main><style jsx>{styles}</style></DashboardShell>}
const styles=`.page{min-height:100%;padding:clamp(12px,2vw,30px);box-sizing:border-box;background:radial-gradient(circle at 90% 10%,rgba(214,173,53,.1),transparent 28%),#022d16;color:#fff}.hero{padding:12px 2px 20px}.hero>span{color:#f0cd61;font-size:9px;font-weight:950;letter-spacing:2px}.hero h2{margin:6px 0;color:#fff;font-size:clamp(24px,3vw,38px)}.hero p{max-width:720px;margin:0;color:#bcd0c4;font-size:12px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.panel{min-width:0;padding:clamp(14px,1.8vw,22px);border:1px solid rgba(240,205,97,.45);border-radius:20px;background:linear-gradient(145deg,rgba(7,95,43,.94),rgba(2,45,22,.98));box-shadow:0 14px 34px rgba(0,0,0,.18);overflow:hidden;animation:rise .45s ease both}.panel:nth-child(2){animation-delay:.06s}.panel:nth-child(3){animation-delay:.12s}.panel:nth-child(4){animation-delay:.18s}.panel header{display:flex;align-items:center;gap:12px;margin-bottom:15px}.icon{width:44px;height:44px;display:grid;place-items:center;flex:0 0 44px;border:1px solid #f0cd61;border-radius:13px;color:#f0cd61;font-size:20px}.panel small{color:#91a99d;font-size:7px;font-weight:900;letter-spacing:1.4px}.panel h3{margin:3px 0 0;font-size:18px}.panel header p{margin:3px 0 0;color:#bcd0c4;font-size:10px}.approval-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.approval{min-height:105px;display:grid;place-items:center;align-content:center;gap:4px;border:1px solid rgba(240,205,97,.22);border-radius:13px;background:rgba(0,0,0,.13)}.approval span{font-size:20px}.approval strong{font-size:23px}.approval small{color:#a8beb1;font-size:8px}.actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.actions a{display:grid;grid-template-columns:28px 1fr auto;align-items:center;gap:7px;min-height:52px;padding:8px 10px;border:1px solid rgba(240,205,97,.22);border-radius:12px;color:#fff;text-decoration:none;background:rgba(0,0,0,.1);transition:transform .2s ease,border-color .2s ease,background .2s ease}.actions a:hover{transform:translateY(-2px);border-color:#f0cd61;background:rgba(240,205,97,.07)}.actions span{font-size:18px}.actions strong{font-size:9px}.actions i{font-style:normal;color:#f0cd61}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@media(max-width:760px){.grid{grid-template-columns:1fr}.approval-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.actions{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.panel,.actions a{animation:none;transition:none}}`;
