"use client";

import DashboardShell from "../../../../components/dashboard/DashboardShell";
import DashboardPager from "../../../../components/dashboard/DashboardPager";
import AIAnalyzer from "../../../../components/dashboard/AIAnalyzer";
import AIPersonalAssistant from "../../../../components/dashboard/AIPersonalAssistant";
import DynamicResultsExplorer from "../../../../components/dashboard/DynamicResultsExplorer";

export default function DashboardIntelligence(){return <DashboardShell role="super_admin" title="Dashboard Intelligence" subtitle="AI analysis, assistance and election results intelligence" activeSection="overview"><main className="page"><DashboardPager current="/super-admin/dashboard/intelligence"/><section className="hero"><span>POLISYNC INTELLIGENCE</span><h2>Decide with better information.</h2><p>Advanced intelligence tools are separated from the main dashboard so every workspace stays focused and comfortable.</p></section><section className="stack"><article className="panel large"><header><div className="icon">✦</div><div><small>01 • AI ANALYSIS</small><h3>AI Election Analyzer</h3><p>Analyze election information without competing with other dashboard components.</p></div></header><AIAnalyzer role="super_admin"/></article><article className="panel"><header><div className="icon">◈</div><div><small>02 • ASSISTANCE</small><h3>AI Personal Assistant</h3></div></header><AIPersonalAssistant/></article><article className="panel wide"><header><div className="icon">📊</div><div><small>03 • RESULTS</small><h3>Election Results Explorer</h3></div></header><DynamicResultsExplorer/></article></section></main><style jsx>{styles}</style></DashboardShell>}
const styles=`.page{min-height:100%;padding:clamp(12px,2vw,30px);box-sizing:border-box;background:radial-gradient(circle at 10% 0%,rgba(34,150,83,.18),transparent 30%),#022d16;color:#fff}.hero{padding:12px 2px 20px}.hero>span{color:#f0cd61;font-size:9px;font-weight:950;letter-spacing:2px}.hero h2{margin:6px 0;color:#fff;font-size:clamp(24px,3vw,38px);line-height:1.05}.hero p{max-width:720px;margin:0;color:#bcd0c4;font-size:12px;line-height:1.6}.stack{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.panel{min-width:0;padding:clamp(14px,1.8vw,22px);border:1px solid rgba(240,205,97,.45);border-radius:20px;background:linear-gradient(145deg,rgba(7,95,43,.94),rgba(2,45,22,.98));box-shadow:0 14px 34px rgba(0,0,0,.18);overflow:hidden;animation:rise .45s ease both}.panel.large,.panel.wide{grid-column:1/-1}.panel:nth-child(2){animation-delay:.06s}.panel:nth-child(3){animation-delay:.12s}.panel header{display:flex;align-items:center;gap:12px;margin-bottom:15px}.icon{width:44px;height:44px;display:grid;place-items:center;flex:0 0 44px;border:1px solid #f0cd61;border-radius:13px;color:#f0cd61;font-size:20px}.panel small{color:#91a99d;font-size:7px;font-weight:900;letter-spacing:1.4px}.panel h3{margin:3px 0 0;font-size:18px}.panel header p{margin:3px 0 0;color:#bcd0c4;font-size:10px}@keyframes rise{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@media(max-width:760px){.stack{grid-template-columns:1fr}.panel.large,.panel.wide{grid-column:auto}}@media(prefers-reduced-motion:reduce){.panel{animation:none}}`;
